config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :classes, :has_many => :lessons
  map.resources :classrooms
  map.resources :contracts
  map.resources :courses
  map.resources :disciplines
  map.resources :lessons
  map.resources :students, :has_many => :contracts
  map.resources :teachers

  

  map.root :controller => "lessons"

  map.connect ':controller/:action.:format'
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  has_and_belongs_to_many :courses, :order => 'name'
  has_and_belongs_to_many :can_be_taught_by, :class_name => 'Teacher', :order => 'name'
  
  validates_presence_of :name
  validates_presence_of :lessons_number
  validates_numericality_of :lessons_number, :greater_than => 0
  
  def to_s
    name
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ResourceController::Base
  use_ajaxian_responses
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
  def title
    _('Disciplines')
  end
end

app/views/disciplines/_form.html.erb
<label class="large"><%=_ 'Name'%> <%= f.text_field :name, :class => "textfield" %></label>
<label class="small"><%=_ 'Lessons Number'%> <%= f.text_field :lessons_number, :class => "textfield" %></label><br />

<fieldset class="clearfix" style="margin: 0 0 10px 0;">
  <legend><%=_ 'Teachers' %></legend>
  <%= collection_multiple_select(:discipline, :can_be_taught_by_ids, Teacher.find(:all, :order => 'name'), :id, :name, :outer_class => 'outer_multiple_select', :inner_class => 'inner_multiple_select') %>	
</fieldset>

app/views/disciplines/edit.html.erb
<div class="box_form">
<%= title_edit :discipline %>
<%= error_messages_for :discipline %>

<% form_for(:discipline, :url => object_url, :html => { :method => :put }) do |f| %>
<fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Atualizar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Cancelar', collection_url %></label>
</fieldset>
<% end %>
</div>

app/views/disciplines/edit.js.erb
<%= title_edit :discipline %>
<%= error_messages_for :discipline %>

<% form_remote_for(:discipline, :url => object_url, :update => "box_form", :html => { :method => :put }) do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= update_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/disciplines/index.html.erb
<%= link_add_to_remote %>

<table class="tbldata">
  <thead>
    <tr>
      <th><%=_ 'Name' %></th>
      <th><%=_ 'Lessons Number' %></th>
      <th><%=_ 'Teachers' %></th>
    </tr>
  </thead>
  <tbody>
    <%- @disciplines.each do |discipline|%>
      <tr>
        <td><%=h discipline.name %></td>
        <td><%=h discipline.lessons_number %></td>
        <td><%=h discipline.can_be_taught_by.join(', ') %></td>
      
        <td><%= link_edit_to_remote(discipline) %></td>
        <td><%= link_delete(discipline) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/disciplines/new.html.erb
<div class="box_form">
<%= title_new :discipline %>
<%= error_messages_for :discipline %>

<% form_for(:discipline, :url => collection_url) do |f| %>
<fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Criar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Cancelar', collection_url %></label>
</fieldset>
<% end %>
</div>

app/views/disciplines/new.js.erb
<%= title_new :discipline %>
<%= error_messages_for :discipline %>

<% form_remote_for(:discipline, :url => collection_url, :update => "box_form") do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= create_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/disciplines/show.html.erb
<p>
  <strong>Name:</strong><%=h @discipline.name %>
</p>
<p>
  <strong>Teacher:</strong><%=h @discipline.teacher %>
</p>

<%= link_to 'Edit', edit_object_url %>
|
<%= link_to 'Back', collection_url %>