config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :classes, :has_many => :lessons
  map.resources :classrooms
  map.resources :contracts
  map.resources :courses
  map.resources :disciplines
  map.resources :lessons
  map.resources :students, :has_many => :contracts
  map.resources :teachers

  

  map.root :controller => "lessons"

  map.connect ':controller/:action.:format'
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :can_teach, :class_name => 'Discipline', :order => 'name'
  
  def to_s
    name
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ResourceController::Base
  use_ajaxian_responses
end

app/helpers/teachers_helper.rb
module TeachersHelper
  def title
    _('Teachers' )
  end
end

app/views/teachers/_form.html.erb
<label class="large"><%=_ 'Name' %> <%= f.text_field :name, :class => "textfield" %></label>
<label class="small"><%=_ 'Autodesk code' %> <%= f.text_field :autodesk_code, :class => "textfield" %></label><br />

<fieldset class="clearfix" style="margin: 0 0 10px 0;">
  <legend><%=_ 'Disciplines' %></legend>
  <%= collection_multiple_select(:teacher, :can_teach_ids, Discipline.find(:all, :order => 'name'), :id, :name, :outer_class => 'outer_multiple_select', :inner_class => 'inner_multiple_select') %>	
</fieldset>

app/views/teachers/edit.html.erb
<div class="box_form">
<%= title_new :teacher %>
<%= error_messages_for :teacher %>

<% form_for(:teacher, :url => object_url, :html => { :method => :put }) do |f| %>
<fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Atualizar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Voltar', collection_url %></label>
</fieldset>
<% end %>
</div>

app/views/teachers/edit.js.erb
<%= title_edit :teacher %>
<%= error_messages_for :teacher %>

<% form_remote_for(:teacher, :url => object_url, :update => "box_form", :html => { :method => :put }) do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= update_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/teachers/index.html.erb
<%= link_add_to_remote %>

<table class="tbldata">
  <thead>
    <tr>
      <th><%=_ 'Name' %></th>
      <th><%=_ 'Autodesk code' %></th>
      <th><%=_ 'Disciplines' %></th>
    </tr>
  </thead>
  <tbody>
    <%- @teachers.each do |teacher|%>
      <tr>
        <td><%=h teacher.name %></td>
        <td><%=h teacher.autodesk_code %></td>
        <td><%=h teacher.can_teach.join(', ') %></td>
      
        <td><%= link_edit_to_remote(teacher) %></td>
        <td><%= link_delete(teacher) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<div class="box_form">
<%= title_new :teacher %>
<%= error_messages_for :teacher %>

<% form_for(:teacher, :url => collection_url) do |f| %>
<fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Criar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Cancelar', collection_url %></label>
</fieldset>
<% end %>
</div>

app/views/teachers/new.js.erb
<%= title_new :teacher %>
<%= error_messages_for :teacher %>

<% form_remote_for(:teacher, :url => collection_url, :update => "box_form") do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= create_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/teachers/show.html.erb
<p>
  <strong>Name:</strong><%=h @teacher.name %>
</p>

<%= link_to 'Edit', edit_object_url %>
|
<%= link_to 'Back', collection_url %>