config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :classes, :has_many => :lessons
  map.resources :classrooms
  map.resources :contracts
  map.resources :courses
  map.resources :disciplines
  map.resources :lessons
  map.resources :students, :has_many => :contracts
  map.resources :teachers

  

  map.root :controller => "lessons"

  map.connect ':controller/:action.:format'
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_and_belongs_to_many :disciplines, :order => 'name'
  
  validates_presence_of :name, :color
  
  def to_s
    name
  end
end

app/controllers/courses_controller.rb
class CoursesController < ResourceController::Base
  use_ajaxian_responses
end

app/helpers/courses_helper.rb
module CoursesHelper
  def title
    _('Courses')
  end
end

app/views/courses/_form.html.erb
<label class="small"><%=_ 'Name' %>
  <%= f.text_field :name, :class => "textfield" %>
</label>

<label class="x-small"><%=_ 'Color' %>
  <%= f.text_field :color, :class => "textfield" %>
</label>

<script type="text/javascript">
// <![CDATA[
  new Control.ColorPicker("course_color", { IMAGE_BASE : "images/colorpicker/" });
// ]]>
</script>
<br/>

<fieldset class="clearfix" style="margin: 0 0 10px 0;">
  <legend><%=_ 'Disciplines' %></legend>
  <%= collection_multiple_select('course', 'discipline_ids', Discipline.find(:all, :order => 'name'), :id, :name, :outer_class => 'outer_multiple_select', :inner_class => 'inner_multiple_select') %>	
</fieldset>

app/views/courses/edit.html.erb
<div class="box_form">
<%= title_edit :course %>
<%= error_messages_for :course %>

<% form_for(:course, :url => object_url, :html => { :method => :put }) do |f| %>
  <fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Atualizar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Voltar', collection_url %></label>
  </fieldset>
<% end %>
</div>
<br/>

<%= link_to 'Show', object_url %>
|
<%= link_to 'Back', collection_url %>

app/views/courses/edit.js.erb
<%= title_edit :course %>
<%= error_messages_for :course %>

<% form_remote_for(:course, :url => object_url, :update => "box_form", :html => { :method => :put }) do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= update_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/courses/index.html.erb
<%= link_add_to_remote %>

<table class="tbldata">
  <thead>
    <tr>
      <th><%=_ 'Name' %></th>
      <th><%=_ 'Disciplines' %></th>
      <th><%=_ 'Color' %></th>
    </tr>
  </thead>
  <tbody>
    <%- @courses.each do |course|%>
      <tr>
        <td><%=h course.name %></td>
        <td><%=h course.disciplines.join(', ') %></td>
        <td style="background-color: #<%=h course.color %>;"><%=h course.color %></td>
      
        <td><%= link_edit_to_remote(course) %></td>
        <td><%= link_delete(course) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<div class="box_form">
<%= title_new :course %>
<%= error_messages_for :course %>

<% form_for(:course, :url => collection_url) do |f| %>
 <fieldset>
  <%= render :partial => "form", :locals => { :f => f } %>
  <label class="x-small lblbutton"><%= submit_tag "Criar", :class => "button" %></label>
  <label class="x-small" style="text-align: right;"><%= link_to 'Cancelar', collection_url %></label>
 </fieldset>
<% end %>
</div>
<br/>
<%= link_to 'Back', collection_url %>

app/views/courses/new.js.erb
<%= title_new :course %>
<%= error_messages_for :course %>

<% form_remote_for(:course, :url => collection_url, :update => "box_form") do |f| %>
  <fieldset>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= create_button_and_cancel_link_to_clear_box_form %>
  </fieldset>
<% end %>

app/views/courses/show.html.erb
<p>
  <strong>Name:</strong><%=h @course.name %>
</p>
<p>
  <strong>Color:</strong><%=h @course.color %>
</p>

<%= link_to 'Edit', edit_object_url %>
|
<%= link_to 'Back', collection_url %>